[package]
name = "cliclient"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "^1", features = ["full"] }
libclient = { path = "../libclient" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"