ERROR_INTERNO = 'error_interno_api'.freeze
API_HTTP_OK = 200
API_HTTP_CREADO = 201
API_HTTP_NO_AUTORIZADO = 401
API_HTTP_RECURSO_RESTRINGIDO = 403
API_HTTP_NO_ENCONTRADO = 404
API_HTTP_ERROR_ESTADO = 409
API_HTTP_ERROR_INTERNO = 500
