export const Genre = {
    FICTION: 'FICTION',
    NON_FICTION: 'NON_FICTION',
    MYSTERY: 'MYSTERY',
    FANTASY: 'FANTASY',
    SCIENCE_FICTION: 'SCIENCE_FICTION',
    BIOGRAPHY: 'BIOGRAPHY',
    HISTORY: 'HISTORY',
    ROMANCE: 'ROMANCE',
    HORROR: 'HORROR',
    SELF_HELP: 'SELF_HELP',
    POETRY: 'POETRY',
    THRILLER: 'THRILLER',
    YOUNG_ADULT: 'YOUNG_ADULT',
    CHILDRENS: 'CHILDRENS',
    CLASSIC: 'CLASSIC',
    GRAPHIC_NOVEL: 'GRAPHIC_NOVEL',
    ADVENTURE: 'ADVENTURE',
    RELIGION: 'RELIGION',
    SCIENCE: 'SCIENCE',
    ART: 'ART',
    PHILOSOPHY: 'PHILOSOPHY',
    COOKING: 'COOKING',
    TRAVEL: 'TRAVEL',
    BUSINESS: 'BUSINESS',
    SPORTS: 'SPORTS'
};

export const GenreLocalized = {
    FICTION: 'Ficción',
    NON_FICTION: 'No ficción',
    MYSTERY: 'Misterio',
    FANTASY: 'Fantasía',
    SCIENCE_FICTION: 'Ciencia ficción',
    BIOGRAPHY: 'Biografía',
    HISTORY: 'Historia',
    ROMANCE: 'Romance',
    HORROR: 'Terror',
    SELF_HELP: 'Autoayuda',
    POETRY: 'Poesía',
    THRILLER: 'Thriller',
    YOUNG_ADULT: 'Joven adulto',
    CHILDRENS: 'Infantil',
    CLASSIC: 'Clásico',
    GRAPHIC_NOVEL: 'Novela gráfica',
    ADVENTURE: 'Aventura',
    RELIGION: 'Religión',
    SCIENCE: 'Ciencia',
    ART: 'Arte',
    PHILOSOPHY: 'Filosofía',
    COOKING: 'Cocina',
    TRAVEL: 'Viajes',
    BUSINESS: 'Negocios',
    SPORTS: 'Deportes'
}