name: tp0
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    networks:
    - testing_net
    ports:
    - 15672:15672
    - 5672:5672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 50s
  input_gateway:
    container_name: input_gateway
    image: input_gateway:latest
    entrypoint: /input_gateway
    environment:
    - CLI_LOG_LEVEL=DEBUG
    - CONSULTA_1_FILTER=1
    - CONSULTA_2_FILTER=1
    - CONSULTA_3_FILTER=1
    - CONSULTA_4_FILTER=1
    - CONSULTA_5_FILTER=1
    - CONSULTA_3_JOIN=1
    - CONSULTA_4_JOIN=1
    - NODO_SIGUIENTE=filter1
    - NODO_ANTERIOR=broker
    - PUERTO=7004
    - PUERTO_SIGUIENTE=7000
    ports:
    - 5000:5000
    - 5001:5001
    - 5002:5002
    - 6000:6000
    networks:
    - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
    - rabbitmq
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - input_gateway_tmp:/tmp/input_gateway_tmp
  output_gateway:
    container_name: output_gateway
    image: output_gateway:latest
    entrypoint: /output_gateway
    environment:
    - CLI_LOG_LEVEL=DEBUG
    - CONSULTA_1_EOF_COUNT=1
    - NODO_SIGUIENTE=broker
    - NODO_ANTERIOR=pnl1
    - PUERTO=7005
    - PUERTO_SIGUIENTE=7006
    ports:
    - 6001:6001
    networks:
    - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
    - rabbitmq
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - output_gateway_tmp:/tmp/output_gateway_tmp
  client_1:
    container_name: client_1
    image: client:latest
    entrypoint: /client
    environment:
    - CLI_LOG_LEVEL=DEBUG
    volumes:
    - ./client/data/movies.csv:/app/data/movies.csv:ro
    - ./client/data/ratings.csv:/app/data/ratings.csv:ro
    - ./client/data/credits.csv:/app/data/credits.csv:ro
    networks:
    - testing_net
    depends_on:
    - input_gateway
    - output_gateway
  filter1:
    container_name: filter1
    image: filter:latest
    entrypoint: python3 workers/filter.py
    environment:
    - WORKER_ID=1
    - WORKER_TYPE=FILTER
    - CONSULTAS=1,2,3,4,5
    - NODO_SIGUIENTE=joiner1
    - NODO_ANTERIOR=input_gateway
    - PUERTO=7000
    - PUERTO_SIGUIENTE=7001
    networks:
    - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  joiner1:
    container_name: joiner1
    image: joiner:latest
    entrypoint: python3 workers/joiner.py
    environment:
    - WORKER_ID=1
    - WORKER_TYPE=JOINER
    - CONSULTAS=3,4
    - EOF_ESPERADOS=3:1,4:1
    - NODO_SIGUIENTE=aggregator1
    - NODO_ANTERIOR=filter1
    - PUERTO=7001
    - PUERTO_SIGUIENTE=7002
    networks:
    - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - joiner1_tmp:/tmp/joiner1_tmp
  aggregator1:
    container_name: aggregator1
    image: aggregator:latest
    entrypoint: python3 workers/aggregator.py
    environment:
    - WORKER_ID=1
    - WORKER_TYPE=AGGREGATOR
    - CONSULTAS=2,3,4,5
    - EOF_ESPERADOS=2:1,3:1,4:1,5:1
    - NODO_SIGUIENTE=pnl1
    - NODO_ANTERIOR=joiner1
    - PUERTO=7002
    - PUERTO_SIGUIENTE=7003
    networks:
    - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - aggregator1_tmp:/tmp/aggregator1_tmp
  pnl1:
    container_name: pnl1
    image: pnl:latest
    entrypoint: python3 workers/pnl.py
    environment:
    - WORKER_ID=1
    - WORKER_TYPE=PNL
    - CONSULTAS=5
    - EOF_ESPERADOS=5:1
    - NODO_SIGUIENTE=output_gateway
    - NODO_ANTERIOR=aggregator1
    - PUERTO=7003
    - PUERTO_SIGUIENTE=7005
    networks:
    - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - pnl1_tmp:/tmp/pnl1_tmp
  broker:
    container_name: broker
    image: broker:latest
    entrypoint: python3 workers/broker.py
    environment:
    - EOF_ESPERADOS=3:1,4:1,5:1
    - EOF_ENVIAR=2:1,3:1,4:1,5:1
    - JOINERS=1:[3, 4]
    - NODO_SIGUIENTE=input_gateway
    - NODO_ANTERIOR=output_gateway
    - PUERTO=7006
    - PUERTO_SIGUIENTE=7004
    networks:
    - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - broker_tmp:/tmp/broker_tmp
networks:
  testing_net:
    ipam:
      driver: default
      config:
      - subnet: 172.25.125.0/24
volumes:
  joiner1_tmp: null
  aggregator1_tmp: null
  pnl1_tmp: null
  broker_tmp: null
  input_gateway_tmp: null
  output_gateway_tmp: null
